import defaultTheme from "tailwindcss/defaultTheme";

/** @type {import('tailwindcss').Config} */
export default {
    darkMode: "class",

    content: [
        "./vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php",
        "./storage/framework/views/*.php",
        "./resources/**/*.blade.php",
        "./resources/**/*.js",
        "./resources/**/*.vue",
    ],
    theme: {
        extend: {
            colors: {
                primary: {
                    50: "#eff6ff",
                    100: "#c3ddfd",
                    200: "#bfdbfe",
                    300: "#93c5fd",
                    400: "#60a5fa",
                    500: "#3b82f6",
                    600: "#2563eb",
                    700: "#1d4ed8",
                    800: "#1e40af",
                    900: "#1e3a8a",
                    950: "#172554",
                },
            },
            fontFamily: {
                body: [
                    "Inter",
                    "ui-sans-serif",
                    "system-ui",
                    "-apple-system",
                    "system-ui",
                    "Segoe UI",
                    "Roboto",
                    "Helvetica Neue",
                    "Arial",
                    "Noto Sans",
                    "sans-serif",
                    "Apple Color Emoji",
                    "Segoe UI Emoji",
                    "Segoe UI Symbol",
                    "Noto Color Emoji",
                ],

                sans: ["Inter", ...defaultTheme.fontFamily.sans],
            },
        },
    },

    plugins: [],
    safelist: [
        "bg-red-50",
        "bg-red-100",
        "bg-red-200",
        "bg-red-300",
        "bg-red-400",
        "bg-red-500",
        "bg-red-600",
        "bg-red-700",
        "bg-red-800",
        "bg-red-900",
        "bg-red-950",

        "text-red-50",
        "text-red-100",
        "text-red-200",
        "text-red-300",
        "text-red-400",
        "text-red-500",
        "text-red-600",
        "text-red-700",
        "text-red-800",
        "text-red-900",
        "text-red-950",

        "dark:bg-red-50",
        "dark:bg-red-100",
        "dark:bg-red-200",
        "dark:bg-red-300",
        "dark:bg-red-400",
        "dark:bg-red-500",
        "dark:bg-red-600",
        "dark:bg-red-700",
        "dark:bg-red-800",
        "dark:bg-red-900",
        "dark:bg-red-950",

        "dark:text-red-50",
        "dark:text-red-100",
        "dark:text-red-200",
        "dark:text-red-300",
        "dark:text-red-400",
        "dark:text-red-500",
        "dark:text-red-600",
        "dark:text-red-700",
        "dark:text-red-800",
        "dark:text-red-900",
        "dark:text-red-950",

        "bg-blue-50",
        "bg-blue-100",
        "bg-blue-200",
        "bg-blue-300",
        "bg-blue-400",
        "bg-blue-500",
        "bg-blue-600",
        "bg-blue-700",
        "bg-blue-800",
        "bg-blue-900",
        "bg-blue-950",

        "text-blue-50",
        "text-blue-100",
        "text-blue-200",
        "text-blue-300",
        "text-blue-400",
        "text-blue-500",
        "text-blue-600",
        "text-blue-700",
        "text-blue-800",
        "text-blue-900",
        "text-blue-950",

        "dark:bg-blue-50",
        "dark:bg-blue-100",
        "dark:bg-blue-200",
        "dark:bg-blue-300",
        "dark:bg-blue-400",
        "dark:bg-blue-500",
        "dark:bg-blue-600",
        "dark:bg-blue-700",
        "dark:bg-blue-800",
        "dark:bg-blue-900",
        "dark:bg-blue-950",

        "dark:text-blue-50",
        "dark:text-blue-100",
        "dark:text-blue-200",
        "dark:text-blue-300",
        "dark:text-blue-400",
        "dark:text-blue-500",
        "dark:text-blue-600",
        "dark:text-blue-700",
        "dark:text-blue-800",
        "dark:text-blue-900",
        "dark:text-blue-950",

        "bg-green-50",
        "bg-green-100",
        "bg-green-200",
        "bg-green-300",
        "bg-green-400",
        "bg-green-500",
        "bg-green-600",
        "bg-green-700",
        "bg-green-800",
        "bg-green-900",
        "bg-green-950",

        "text-green-50",
        "text-green-100",
        "text-green-200",
        "text-green-300",
        "text-green-400",
        "text-green-500",
        "text-green-600",
        "text-green-700",
        "text-green-800",
        "text-green-900",
        "text-green-950",

        "dark:bg-green-50",
        "dark:bg-green-100",
        "dark:bg-green-200",
        "dark:bg-green-300",
        "dark:bg-green-400",
        "dark:bg-green-500",
        "dark:bg-green-600",
        "dark:bg-green-700",
        "dark:bg-green-800",
        "dark:bg-green-900",
        "dark:bg-green-950",

        "dark:text-green-50",
        "dark:text-green-100",
        "dark:text-green-200",
        "dark:text-green-300",
        "dark:text-green-400",
        "dark:text-green-500",
        "dark:text-green-600",
        "dark:text-green-700",
        "dark:text-green-800",
        "dark:text-green-900",
        "dark:text-green-950",

        "bg-purple-50",
        "bg-purple-100",
        "bg-purple-200",
        "bg-purple-300",
        "bg-purple-400",
        "bg-purple-500",
        "bg-purple-600",
        "bg-purple-700",
        "bg-purple-800",
        "bg-purple-900",
        "bg-purple-950",

        "text-purple-50",
        "text-purple-100",
        "text-purple-200",
        "text-purple-300",
        "text-purple-400",
        "text-purple-500",
        "text-purple-600",
        "text-purple-700",
        "text-purple-800",
        "text-purple-900",
        "text-purple-950",

        "dark:bg-purple-50",
        "dark:bg-purple-100",
        "dark:bg-purple-200",
        "dark:bg-purple-300",
        "dark:bg-purple-400",
        "dark:bg-purple-500",
        "dark:bg-purple-600",
        "dark:bg-purple-700",
        "dark:bg-purple-800",
        "dark:bg-purple-900",
        "dark:bg-purple-950",

        "dark:text-purple-50",
        "dark:text-purple-100",
        "dark:text-purple-200",
        "dark:text-purple-300",
        "dark:text-purple-400",
        "dark:text-purple-500",
        "dark:text-purple-600",
        "dark:text-purple-700",
        "dark:text-purple-800",
        "dark:text-purple-900",
        "dark:text-purple-950",

        "bg-orange-50",
        "bg-orange-100",
        "bg-orange-200",
        "bg-orange-300",
        "bg-orange-400",
        "bg-orange-500",
        "bg-orange-600",
        "bg-orange-700",
        "bg-orange-800",
        "bg-orange-900",
        "bg-orange-950",

        "text-orange-50",
        "text-orange-100",
        "text-orange-200",
        "text-orange-300",
        "text-orange-400",
        "text-orange-500",
        "text-orange-600",
        "text-orange-700",
        "text-orange-800",
        "text-orange-900",
        "text-orange-950",

        "dark:bg-orange-50",
        "dark:bg-orange-100",
        "dark:bg-orange-200",
        "dark:bg-orange-300",
        "dark:bg-orange-400",
        "dark:bg-orange-500",
        "dark:bg-orange-600",
        "dark:bg-orange-700",
        "dark:bg-orange-800",
        "dark:bg-orange-900",
        "dark:bg-orange-950",

        "dark:text-orange-50",
        "dark:text-orange-100",
        "dark:text-orange-200",
        "dark:text-orange-300",
        "dark:text-orange-400",
        "dark:text-orange-500",
        "dark:text-orange-600",
        "dark:text-orange-700",
        "dark:text-orange-800",
        "dark:text-orange-900",
        "dark:text-orange-950",
    ],
};
